### PR TITLE
Use parent class java.lang.Throwable

### PR DESCRIPTION
**Pull request by tangrammer**
Remove duplicated catching approach

### CODE REVIEW

**Comment by martinklepsch** [comment]
@tangrammer Hey! Thanks for opening a PR and helping to maintain this library :) 

A cursory look at Java docs seem to indicate that `Exception` is not a subclass of `Error`. I've previously caught `Throwable` when I wanted to catch exceptions and asserts but I think that's also not really recommended. 

Can you explain a bit more what motivated this change?

**Comment by tangrammer** [comment]
reading a bit about the reasoning behind not using Throwable it seems to me that it doesn't apply to current code thus it throws the exception at the end 🤔

**Comment by martinklepsch** [comment]
Can you explain why this change is necessary? I see that it catches a broader set of `Error` instances but I'm hesitant to just add it "for the sake of it". Feedback by other users of this library is welcome as well of course.

**Comment by tangrammer** [comment]
IMO the change is not necessary as far as it doesn't change the behavior at all, it could be considered a code improvement if you consider it... anyway don't think it deserves so much discussion ... feel free to close the PR at any time :)

**Pull request closed without merging**
