### PR TITLE
Fix a parsing bug for project-id

### PR DESCRIPTION
**Pull request by emil0r**
Sentry.io has started to give out project numbers that are bigger than an integer. This patch changes the parsing of the project id to a long, instead of an integer.

In addition, the few dependencies that exists are upgraded to the latest version, with a special mention to clj-http-lite. The clj-commons version is used there, as it is maintained.

### CODE REVIEW

**Review by martinklepsch — COMMENTED** [review]
Thanks for the PR and the ping on Slack, my GitHub notifications are somewhat unmonitored these days 🙂 

Would you mind also updating the changelog? Then I'll try to merge + cut a release asap :)

**Comment by emil0r** [comment]
Sorry that it took a while. Been a bit busy :)

**Comment by awebneck** [comment]
Any news on getting this merged and released?

**Comment by emil0r** [comment]
Ping @martinklepsch :)

**Comment by martinklepsch** [comment]
@emil0r Thanks for the PR and adjustments & sorry it's been taking so long. I've tried to deploy the new version to Clojars today but am encountering [an issue with `boot`'s deploy tooling](https://github.com/boot-clj/boot/issues/745) that I'm not able to get around by pinning Boot to a lower version.

I know this is a stretch but would you be interested in helping get the deployment tooling for this project running again? I'm pretty open as to what tool to use.

**Comment by emil0r** [comment]
I can take a look. Looking into boot it seems to be fairly dead. So either lein or the new CLI tools. Do you want to keep boot for the other parts?

**Comment by emil0r** [comment]
Noted.

**Comment by emil0r** [comment]
@awebneck https://github.com/sethtrain/raven-clj/pull/34

**Pull request merged**
